name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['stable', 'nightly']

    steps:
    - uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim_version }}

    - name: Install Lua and LuaRocks
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        # Install luacheck for linting
        luarocks install luacheck
        
        # Install plenary for testing using our Makefile
        make install-dev

    - name: Install stylua
      run: |
        curl -L -o stylua.zip https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
        unzip stylua.zip
        chmod +x stylua
        sudo mv stylua /usr/local/bin/

    - name: Run CI checks
      run: make ci

  compatibility:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Test Neovim 0.7 compatibility
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: 'v0.7.0'

    - name: Install plenary
      run: |
        mkdir -p ~/.local/share/nvim/lazy
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/lazy/plenary.nvim

    - name: Test basic functionality
      run: |
        nvim --version
        nvim --headless --noplugin -u tests/minimal_init.lua -c "lua print('Testing basic load...'); require('neochange'); print('Success!')" -c "qall"