name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this release
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ### Using lazy.nvim
          ```lua
          {
            "yourusername/neochange.nvim",
            tag = "${{ github.ref_name }}",
            config = function()
              require('neochange.commands').setup()
            end
          }
          ```
          
          ## Documentation
          
          Run `:h neochange` for complete documentation.
        draft: false
        prerelease: false