name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const tag = context.ref.replace('refs/tags/', '');
          await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: tag,
            name: `Release ${tag}`,
            body: `## Changes in this release
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ### Using lazy.nvim
          \`\`\`lua
          {
            "${context.repo.owner}/${context.repo.repo}",
            tag = "${tag}",
            config = function()
              require('neochange.commands').setup()
            end
          }
          \`\`\`
          
          ## Documentation
          
          Run \`:h neochange\` for complete documentation.`,
            draft: false,
            prerelease: false
          });